### ISSUE TITLE
Broken Links in `docs` Directory

### ISSUE THREAD

**Issue by geofis** [sparkfun/SparkFun_UM980_Triband_GNSS_RTK_Breakout#1]
Hello.

Thank you for creating this repository.

Please note that many links in the `docs` Markdown files are broken. It appears that the URLs were initially pointing to a directory structure that did not include the `docs` root.

José.

**Comment by nseidle** [comment]
Can you give me an example of one?

**Comment by geofis** [comment]
Sure. For example, in [this page](https://github.com/sparkfun/SparkFun_UM980_Triband_GNSS_RTK_Breakout/blob/main/docs/arduino_examples.md) the link to [Arduino Output - UM980 Example 1](https://github.com/sparkfun/SparkFun_UM980_Triband_GNSS_RTK_Breakout/blob/main/assets/img/Arduino_Output_Ex_1_ESP32_Triband_GNSS_RTK_UM980.JPG) seems broken from my side.

![imagen](https://github.com/sparkfun/SparkFun_UM980_Triband_GNSS_RTK_Breakout/assets/13460617/e73ebef1-0d0c-4f27-afc7-ff8de2c089d3)

![imagen](https://github.com/sparkfun/SparkFun_UM980_Triband_GNSS_RTK_Breakout/assets/13460617/83c37adc-d235-4e72-8756-2462556677f2)

**Comment by nseidle** [comment]
Ah, you're viewing the source files directly. They won't render. The docs are mkdocs and are meant to be viewed from [here](https://docs.sparkfun.com/SparkFun_UM980_Triband_GNSS_RTK_Breakout/introduction/). Let me know what lead you to believe you should be inside the source markdown files.

**Comment by geofis** [comment]
Ah, now I understand. I mistakenly thought the repository would render, since I accessed it externally. Sorry for the confusion, and thank you for the clarification.
