### ISSUE TITLE
UM980 Firmware and Uprecise Version are Outdated

### ISSUE THREAD

**Issue by simeononsecurity** [sparkfun/SparkFun_UM980_Triband_GNSS_RTK_Breakout#2]
I recently picked up the SparkFun UM980 for a project since I often use sparkfun products and have experience with the UM980 and UM982. However, I've noticed that after updating (or so I thought) the firmware as provided in this repo, it's actually an much older version than what I already had on other comparable devices. 

Is there a later firmware that can be provided at all? 

Additionally, if you search hard enough, you can get a [v2 version of UPrecise](http://www.eltehs.lv/UPrecise-V2.0.802.zip) that has many QoL improvements and new features over the V1 doesn't have. 
I get Unicorecomm makes some things private or just flat out doesn't update their documentation. But if sparkfun could provide these I'm sure that the community would benefit from it.

**Comment by nseidle** [comment]
Sorry for the confusion! Please see the docs for [updating the UM980 in the RTK Torch](https://docs.sparkfun.com/SparkFun_RTK_Everywhere_Firmware/firmware_update/#updating-um980-firmware). We've put all the firmware that we've come across in the [Torch repo](https://github.com/sparkfun/SparkFun_RTK_Torch/tree/main/UM980_Firmware) including v2 of U-Precise. Once upgraded, be sure to have some fun with [HAS E6](https://github.com/sparkfun/SparkFun_UM980_Galileo_HAS_E6_Convergence_Test).

I'll leave this issue open until we can get proper documentation for updating the UM980 into the product docs.

**Comment by bboyho** [comment]
@simeononsecurity Sorry, I didn't realize that Unicore Communications updated their software and firmware. I have updated the links in this tutorial, product page, and screenshots to reflect the changes.

**Comment by nseidle** [comment]
I'm updating this issue with the [Firmware Update](https://docs.sparkfun.com/SparkFun_UM980_Triband_GNSS_RTK_Breakout/firmware_update/) update. Hah!

Thanks @bboyho!
